---
- name: Change Soft Open File Limit
  lineinfile: dest=/etc/security/limits.conf
              insertbefore="^# End of file$"
              line="root   soft    nofile  40000"
              state=present

- name: Change Hard Open File Limit
  lineinfile: dest=/etc/security/limits.conf
              insertbefore="^# End of file$"
              line="root   hard    nofile  40000"
              state=present

- name: Change Hard Open File Limit
  lineinfile: dest=/etc/pam.d/su
              insertafter="^# session    required   pam_limits.so$"
              line="session    required   pam_limits.so"
              state=present

- name: Create directory structure
  file: state=directory
        path=/opt/neo4j

- name: Download neo4j
  get_url: url=http://dist.neo4j.org/neo4j-community-{{ neo4j_version }}-unix.tar.gz
           dest=/opt/neo4j/neo4j-community-{{ neo4j_version }}-unix.tar.gz

- name: Unzip
  command: tar xvzf neo4j-community-{{ neo4j_version }}-unix.tar.gz chdir=/opt/neo4j

- name: Remove tar file
  command: rm -rf /opt/neo4j/neo4j-community-{{ neo4j_version }}-unix.tar.gz

- name: Allow access from ALL hosts
  lineinfile: dest=/opt/neo4j/neo4j-community-{{ neo4j_version }}/conf/neo4j-server.properties
              insertafter="^#org.neo4j.server.webserver.address=0.0.0.0$"
              line=org.neo4j.server.webserver.address=0.0.0.0
              state=present

- name: Set port listening
  lineinfile: dest=/opt/neo4j/neo4j-community-{{ neo4j_version }}/conf/neo4j-server.properties
              regexp="^org.neo4j.server.webserver.port=7474$"
              line=org.neo4j.server.webserver.port=80
              state=present

- name: Copy Upstart Job
  copy: src=../files/neo4j.conf dest=/etc/init/neo4j.conf owner=root group=root mode=0644

- name: Start
  command: sudo start neo4j
